airflow:
  airflow:
    defaultNodeSelector:
      application/type: infra
    users:
      - username: admin
        password: "${ADMIN_PASSWORD_TEMP}"
        role: Admin
        email: admin@localhost
        firstName: admin
        lastName: admin
    usersTemplates:
      ADMIN_PASSWORD_TEMP:
        kind: secret
        name: airflow-secrets
        key: openmetadata-airflow-password
  dags:
    persistence:
      storageClass: efs-sc
  logs:
    persistence:
      storageClass: efs-sc
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::828524833368:role/eksctl-analytics-non-prod-eks-addon-iamservi-Role1-1RYV3FOK9ON2F"
  web:
    extraVolumes:
    - name: spc
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: openmetadata-deps-spc
    extraVolumeMounts:
    - name: spc
      mountPath: /mnt/secret-store
mysql:
  primary:
    nodeSelector:
      application/type: infra
  global:
    storageClass: efs-sc
  auth:
    existingSecret: mysql
elasticsearch:
  nodeSelector:
    application/type: infra
  volumeClaimTemplate:
    storageClassName: efs-sc
secretProviderClass:
  name: openmetadata-deps-spc
  provider: aws
  region: ap-southeast-1
  awsSecretName: ae_openmetadata
  secrets:
    - secretName: mysql
      keyObjects:
        - key: mysql-password
          objectName: mysql_password
        - key: mysql-root-password
          objectName: mysql_root_password


