apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hiveMetastore.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
    app.kubernetes.io/component: metastore
    {{- include "hiveMetastore.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
      app.kubernetes.io/component: metastore
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ include "hiveMetastore.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hiveMetastore.name" . }}
        app.kubernetes.io/component: metastore
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      serviceAccountName: {{ .Release.Name }}-csi-sa
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
      - name: metastore
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env: 
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretProviderClass.secretName | quote }}
              key: hive_db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretProviderClass.secretName | quote }}
              key: hive_db_pass
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretProviderClass.secretName | quote }}
              key: hive_db_name
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretProviderClass.secretName | quote }}
              key: s3_access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretProviderClass.secretName | quote }}
              key: s3_secret_key
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretProviderClass.secretName | quote }}
              key: s3_endpoint
              
        command:
        - "/bin/sh"
        - "-c"
        - "envsubst < /opt/hive/conf-env/hive-site-env.xml > /opt/hive/conf/hive-site.xml && /opt/hive/bin/hive --service metastore"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: hive-config
          mountPath: /opt/hive/conf-env
        - name: hive-secret
          mountPath: /mnt/secret-store

      volumes:
      - name: hive-config
        configMap:
          name: {{ include "hiveMetastore.fullname" . }}
      - name: hive-secret
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.secretProviderClass.name | quote }}
