apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
   name: {{ .Values.secretProviderClass.name | quote }}
   namespace: {{ .Release.Namespace | quote }}
spec:
  provider: {{ .Values.secretProviderClass.provider | quote }}
  parameters:
    region: {{ .Values.secretProviderClass.region | quote }}
    objects: |
      - objectName: {{ .Values.secretProviderClass.awsSecretName | quote }}
        objectType: "secretsmanager"
        jmesPath:
        {{- range .Values.secretProviderClass.secrets }}
        {{- range .keyObjects }}
        - path: {{ .objectName | quote }}
          objectAlias: {{ .aliasName | quote }}
        {{- end }}
        {{- end }}
  secretObjects:
  {{- range .Values.secretProviderClass.secrets }}
  - data:
    {{- range .keyObjects }}
    - key: {{ .key | quote }}
      objectName: {{ .aliasName | quote }}
    {{- end }}
    secretName: {{ .secretName | quote }}
    type: Opaque
  {{- end }}