apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ranger.fullname" . }}
  labels:
    {{- include "ranger.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ranger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ranger.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ranger.serviceAccountName" . }}
      
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /opt/apache-ranger/ranger-current-admin/install.properties
              subPath: install_properties
          ports:
            - name: http
              containerPort: 6080
              protocol: TCP
          # livenessProbe:
          #   initialDelaySeconds: 6000000
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - "sh"
            - "-c"
            - | 
              export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
              export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"
              echo $HADOOP_OPTS
              ./docker-entrypoint.sh
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: config-volume
          configMap:
            name: {{ include "ranger.fullname" . }}